<?php

namespace DoctrineProxies\__CG__\SubItem\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SubItem extends \SubItem\Entity\SubItem implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'label', 'parentResourceTemplate', 'childResourceTemplate', 'connectingProperty', 'labelProperty', 'codeProperty', 'codeTemplate', 'owner'];
        }

        return ['__isInitialized__', 'id', 'label', 'parentResourceTemplate', 'childResourceTemplate', 'connectingProperty', 'labelProperty', 'codeProperty', 'codeTemplate', 'owner'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SubItem $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabel($label)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabel', [$label]);

        return parent::setLabel($label);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', []);

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner($owner = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', [$owner]);

        return parent::setOwner($owner);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', []);

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function getConnectingProperty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConnectingProperty', []);

        return parent::getConnectingProperty();
    }

    /**
     * {@inheritDoc}
     */
    public function setConnectingProperty($prop = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConnectingProperty', [$prop]);

        return parent::setConnectingProperty($prop);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabelProperty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabelProperty', []);

        return parent::getLabelProperty();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabelProperty($prop = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabelProperty', [$prop]);

        return parent::setLabelProperty($prop);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeProperty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeProperty', []);

        return parent::getCodeProperty();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeProperty($prop = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeProperty', [$prop]);

        return parent::setCodeProperty($prop);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentResourceTemplate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentResourceTemplate', []);

        return parent::getParentResourceTemplate();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentResourceTemplate($resourceTemplate = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentResourceTemplate', [$resourceTemplate]);

        return parent::setParentResourceTemplate($resourceTemplate);
    }

    /**
     * {@inheritDoc}
     */
    public function getChildResourceTemplate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChildResourceTemplate', []);

        return parent::getChildResourceTemplate();
    }

    /**
     * {@inheritDoc}
     */
    public function setChildResourceTemplate($resourceTemplate = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChildResourceTemplate', [$resourceTemplate]);

        return parent::setChildResourceTemplate($resourceTemplate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeTemplate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeTemplate', []);

        return parent::getCodeTemplate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeTemplate($template)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeTemplate', [$template]);

        return parent::setCodeTemplate($template);
    }

    /**
     * {@inheritDoc}
     */
    public function getResourceId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResourceId', []);

        return parent::getResourceId();
    }

}
